version: '3.8'
services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./scripts/initdb:/docker-entrypoint-initdb.d:ro
      - ./scripts:/root/data
    ports:
      - 5432:5432
