version: 0.2

phases:
  install:
    commands:
      - echo "Installing packages"
  build:
    commands:
      - aws ssm get-parameter --name $BROADCAST_API_KEY --with-decryption --query "Parameter.Value" | jq -r
