version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12

  pre_build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - VENV_TESTS='/venv/eas-tests'
      - python3.12 -m venv $VENV_TESTS
      - . $VENV_TESTS/bin/activate
      - chmod +x environment.sh
      - . ./environment.sh
      - make bootstrap

  build:
    on-failure: CONTINUE
    commands:
      - export CI=true # Switch to headless mode
      - |
        if [ "$ENABLE_CBC_INTEGRATION_TESTS" = "false" ]; then
          export DISABLED_TEST_SUITES="cbc_integration top_rail"
        else
          export DISABLED_TEST_SUITES="top_rail"
        fi

        export DISABLED_TEST_SUITES="auth_flow broadcast_flow cbc_integration links_and_cookies platform_admin_flow template_flow throttling top_rail user_operations"

        echo "Disabled test suites: $DISABLED_TEST_SUITES"
      - make test; exit 0
      - echo "Test run finished."
      - python3.12 ./scripts/report-test-results.py functional-test-reports

  post_build:
    commands:
      - python3.12 ./scripts/signal-build-pass-or-fail.py $(pwd) report.xml

artifacts:
  files:
    - "**/*"

  secondary-artifacts:
    TestOutput:
      files:
        - functional-test-reports/*
        - functional-test-traces/**/*
      name: All Test Output

    FailedTestOutput:
      files:
        - functional-test-reports/*
        - functional-test-traces/failed/*
      name: Failed Test Output

reports:
  functional-test-reports:
    files:
      - "*.xml"
    base-directory: functional-test-reports
    discard-paths: yes
    file-format: JUNITXML
