version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - cd /tmp/
      - sudo wget https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
      - sudo unzip chromedriver_linux64.zip
      - sudo mv chromedriver /usr/bin/chromedriver
      - chromedriver --version

      - sudo curl https://intoli.com/install-google-chrome.sh | bash
      - sudo mv /usr/bin/google-chrome-stable /usr/bin/google-chrome
      - google-chrome --version && which google-chrome
  pre_build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - VENV_TESTS='/venv/eas-tests'
      - python3.11 -m venv $VENV_TESTS
      - . $VENV_TESTS/bin/activate
  build:
    commands:
      - chmod +x environment.sh
      - . ./environment.sh
      - export BROADCAST_SERVICE_API_KEY=$(aws ssm get-parameter --name $BROADCAST_API_KEY --with-decryption --query "Parameter.Value" | jq -r)
      - export ENVIRONMENT=preview
      - python3.11 -m pip install --upgrade pip wheel setuptools
      - make bootstrap
      - make test
  post_build:
    commands:
      - echo "Testing passed" > screenshots/success.txt

artifacts:
  files:
    - screenshots/*
