version: 0.2

env:
  variables:
    testsuites: >-
      template-flow

phases:
  install:
    runtime-versions:
      python: 3.9

    commands:
      - apt update
      - apt install -y xvfb libxi6 libgconf-2-4 libnss3
      - cd /tmp/
      - wget https://storage.googleapis.com/chrome-for-testing-public/122.0.6261.128/linux64/chromedriver-linux64.zip
      - unzip chromedriver-linux64.zip
      - mv chromedriver-linux64 chromedriver
      - mv chromedriver /usr/bin/chromedriver
      - apt-get install -f -y

  pre_build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - VENV_TESTS='/venv/eas-tests'
      - python3.9 -m venv $VENV_TESTS
      - . $VENV_TESTS/bin/activate
      - chmod +x environment.sh
      - . ./environment.sh
      - export ENVIRONMENT=preview
      - python3.9 -m pip install --upgrade pip wheel setuptools
      - make bootstrap

  build:
    on-failure: CONTINUE
    commands:
      # - make test-broadcast-flow; exit 0
      # - make test-cbc-integration; exit 0
      # - make test-platform-admin-flow; exit 0
      # - make test-authentication-flow; exit 0
      # # - make test-top-rail-services; exit 0
      # - make test-links-and-cookies; exit 0
      - make test-template-flow; exit 0
      - echo "Test run completed."
      - touch "$(pwd)/test-failures"
      - chmod +rw "$(pwd)/test-failures"
      - python3.9 ./scripts/collect-failure-data.py $(pwd) $testsuites
      - python3.9 ./scripts/report-test-failures.py "$(pwd)/test-failures"

  post_build:
    commands:
      - python3.9 ./scripts/signal-build-pass-or-fail.py $(pwd) $testsuites

artifacts:
  files:
    - screenshots/*
    - functional-test-reports/*
    - test-failures
