version: 0.2

env:
  variables:
    testsuites: >-
      broadcast-flow
      platform-admin-flow
      authentication-flow
      links-and-cookies
      template-flow
      user-operations
      throttling
      session-timeout

phases:
  install:
    runtime-versions:
      python: 3.12

  pre_build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - VENV_TESTS='/venv/eas-tests'
      - python3.12 -m venv $VENV_TESTS
      - . $VENV_TESTS/bin/activate
      - chmod +x environment.sh
      - . ./environment.sh
      - python3.12 -m pip install --upgrade pip wheel setuptools
      - make bootstrap

  build:
    on-failure: CONTINUE
    commands:
      # Need to add CBC integration into the list of test reports, in the proper place, if it is executed - hence the below
      # The if below doesn't check for truthiness, but instead "true", because CodePipeline *requires* a value - therefore it will *always* be truthy.
      - export CI=true # Switch to headless mode
      - make test-broadcast-flow; exit 0
      - |
        if [ "$ENABLE_CBC_INTEGRATION_TESTS" = "true" ]; then
          make test-cbc-integration; exit 0
        else
          echo "SKIPPING WORKFLOW 'test-cbc-integration'..."
        fi
      - make test-platform-admin-flow; exit 0
      - make test-authentication-flow; exit 0
      - make test-links-and-cookies; exit 0
      - make test-template-flow; exit 0
      - make test-user-operations; exit 0
      - make test-throttling; exit 0
      - make test-session-timeout; exit 0
      - echo "Test run completed."
      - python3.12 ./scripts/report-test-results.py functional-test-reports

  post_build:
    commands:
      # CodeBuild doesn't like that the reports don't have a .xml extension
      # ...and silently fails to report any test contents. Just an empty report.
      - |
        for file in functional-test-reports/*; do
          cp "$file" "${file}.xml"
        done

      - |
        if [ "$ENABLE_CBC_INTEGRATION_TESTS" = "true" ]; then
          export testsuites="$testsuites cbc-integration"
        fi
      - python3.12 ./scripts/signal-build-pass-or-fail.py $(pwd) $testsuites

artifacts:
  files:
    - functional-test-reports/*
    - functional-test-traces/**/*

reports:
  functional-test-reports:
    files:
      - "*.xml"
    base-directory: functional-test-reports
    discard-paths: yes
    file-format: JUNITXML
