version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - apt update
      - apt install -y xvfb libxi6 libgconf-2-4 libnss3
      - cd /tmp/
      - wget https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
      - unzip chromedriver_linux64.zip
      - mv chromedriver /usr/bin/chromedriver
      - apt-get install -f -y
  pre_build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - VENV_TESTS='/venv/eas-tests'
      - python3.9 -m venv $VENV_TESTS
      - . $VENV_TESTS/bin/activate
  build:
    commands:
      - chmod +x environment.sh
      - . ./environment.sh
      - export ENVIRONMENT=preview
      - python3.9 -m pip install --upgrade pip wheel setuptools
      - make bootstrap
      - make test-broadcast-flow
  post_build:
    commands:
      - echo "Testing passed" > screenshots/success.txt

reports:
  pytest_reports:
    files:
      - broadcast-flow
      - admin-flow
      - cbc_integration
    base-directory: functional-test-reports
    file-format: JUNITXML

artifacts:
  files:
    - screenshots/*
